name: Gentx
on: [pull_request]
jobs:
  validate-gentx:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.15.6
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Display go version
        run: go version
      - name: validate-gentx
        run: |
          bash -x ./scripts/validate-gentx.sh
